import { Column, Entity, JoinColumn, ManyToOne, Index } from 'typeorm';
import { BaseEntity } from '../../shared/entities/base.entity';
import { Tenant } from '../../tenants/entities/tenant.entity';
import { Vehicle } from './vehicle.entity';
import { Location } from './location.entity';

export enum InsightType {
  UNDERPRICED = 'underpriced',
  OVERPRICED = 'overpriced',
  IDLE_VEHICLE = 'idle_vehicle',
  HIGH_DEMAND = 'high_demand',
  LOW_DEMAND = 'low_demand',
  SEASONAL_TREND = 'seasonal_trend',
  LOCATION_DEMAND = 'location_demand',
}

export enum InsightSeverity {
  INFO = 'info',
  WARNING = 'warning',
  CRITICAL = 'critical',
}

export enum InsightStatus {
  ACTIVE = 'active',
  ACKNOWLEDGED = 'acknowledged',
  RESOLVED = 'resolved',
  DISMISSED = 'dismissed',
}

/**
 * Pricing and occupancy insights/recommendations
 * Generated by rule engine, includes reasoning text
 */
@Entity({ name: 'pricing_insights' })
@Index(['tenantId', 'vehicleId'])
@Index(['tenantId', 'type'])
@Index(['tenantId', 'status'])
@Index(['tenantId', 'severity'])
export class PricingInsight extends BaseEntity {
  @ManyToOne(() => Tenant, { nullable: false })
  @JoinColumn({ name: 'tenant_id' })
  tenant!: Tenant;

  @Column({ name: 'tenant_id' })
  tenantId!: string;

  @ManyToOne(() => Vehicle, { nullable: true })
  @JoinColumn({ name: 'vehicle_id' })
  vehicle?: Vehicle | null;

  @Column({ name: 'vehicle_id', nullable: true })
  vehicleId?: string | null;

  @ManyToOne(() => Location, { nullable: true })
  @JoinColumn({ name: 'location_id' })
  location?: Location | null;

  @Column({ name: 'location_id', nullable: true })
  locationId?: string | null;

  @Column({ type: 'enum', enum: InsightType })
  type!: InsightType;

  @Column({ type: 'enum', enum: InsightSeverity, default: InsightSeverity.INFO })
  severity!: InsightSeverity;

  @Column({ type: 'enum', enum: InsightStatus, default: InsightStatus.ACTIVE })
  status!: InsightStatus;

  @Column({ type: 'varchar', length: 200 })
  title!: string; // Short title (e.g., "Vehicle Underpriced")

  @Column({ type: 'text' })
  reasoning!: string; // Detailed explanation

  // Metrics
  @Column({ name: 'current_price', type: 'decimal', precision: 10, scale: 2, nullable: true })
  currentPrice?: number | null;

  @Column({ name: 'recommended_price', type: 'decimal', precision: 10, scale: 2, nullable: true })
  recommendedPrice?: number | null;

  @Column({ name: 'market_average_price', type: 'decimal', precision: 10, scale: 2, nullable: true })
  marketAveragePrice?: number | null;

  @Column({ name: 'occupancy_rate', type: 'decimal', precision: 5, scale: 2, nullable: true })
  occupancyRate?: number | null; // 0-100

  @Column({ name: 'idle_days', type: 'int', nullable: true })
  idleDays?: number | null;

  @Column({ name: 'demand_score', type: 'decimal', precision: 5, scale: 2, nullable: true })
  demandScore?: number | null; // 0-100

  // Date range for analysis
  @Column({ name: 'analysis_start_date', type: 'date', nullable: true })
  analysisStartDate?: Date | null;

  @Column({ name: 'analysis_end_date', type: 'date', nullable: true })
  analysisEndDate?: Date | null;

  // Suggested dates for high demand
  @Column({ name: 'suggested_dates', type: 'jsonb', nullable: true })
  suggestedDates?: Array<{
    date: string; // YYYY-MM-DD
    expectedDemand: number; // 0-100
    recommendedPrice?: number;
    reason: string;
  }> | null;

  // Additional context data
  @Column({ name: 'context_data', type: 'jsonb', nullable: true })
  contextData?: Record<string, any> | null;

  // Acknowledgment
  @Column({ name: 'acknowledged_at', type: 'timestamp', nullable: true })
  acknowledgedAt?: Date | null;

  @Column({ name: 'acknowledged_by_user_id', type: 'uuid', nullable: true })
  acknowledgedByUserId?: string | null;

  @Column({ name: 'resolved_at', type: 'timestamp', nullable: true })
  resolvedAt?: Date | null;

  @Column({ name: 'resolved_by_user_id', type: 'uuid', nullable: true })
  resolvedByUserId?: string | null;
}

